### ISSUE TITLE
location should be optional for add_bucket

### ISSUE THREAD

**Issue by ThinkerYzu** [leejo/AWS-S3#11]
https://metacpan.org/source/LEEJO/AWS-S3-0.16/lib/AWS/S3.pm#L94
This line made location mandatory, however, it should be optional.

https://metacpan.org/source/LEEJO/AWS-S3-0.16/lib/AWS/S3/Request/CreateBucket.pm#L18
If a caller doesn't give location, then undef will be pass to this attribute, and fail the check.

This problem was fixed before, but why it come out again.
https://github.com/leejo/AWS-S3/issues/9

**Comment by leejo** [comment]
@ThinkerYzu - do you have a test case / example code for this? The type constraint on location is `Maybe[Str]` so passing `undef` shouldn't fail that constraint.

**Comment by ThinkerYzu** [comment]
The code looks like,

        $s3->add_bucket(name => 'foobar-test');

Following lines are the error message.


    error in _try_process_thread: Attribute (location) does not pass the type constraint because: Validation failed for 'Str' with value undef at constructor AWS::S3::Request::CreateBucket::new (defined at /usr/lib/.../5.24.3/libraries/active/lib/perl5/AWS/S3/Request/CreateBucket.pm line 64) line 69

      AWS::S3::Request::CreateBucket::new('AWS::S3::Request::CreateBucket', 'bucket', 'foobar-test', 'location', undef, 's3', 'AWS::S3=HASH(0x7f32913efc48)', 'type', 'CreateBucket') called at /usr/lib/.../5.24.3/libraries/active/lib/perl5/AWS/S3.pm line 45

      AWS::S3::request('AWS::S3=HASH(0x7f32913efc48)', 'CreateBucket', 'bucket', 'foobar-test', 'location', undef) called at /usr/lib/.../5.24.3/libraries/active/lib/perl5/AWS/S3.pm line 94

      AWS::S3::add_bucket('AWS::S3=HASH(0x7f32913efc48)', 'name', 'foobar-test') called at /...                                   

      ...

It would work if I give an empty location.

      $s3->add_bucket(name => 'foobar-test', location => '')

**Comment by leejo** [comment]
What version of the library are you using?

**Comment by ThinkerYzu** [comment]
I think it is in different version.  Sorry for that.
