### ISSUE TITLE
AWS::S3::Bucket->file() doesn't handle keys with leading '/' correctly.

### ISSUE THREAD

**Issue by ThinkerYzu** [leejo/AWS-S3#12]
Keys of S3 should be any utf-8 string according the document of Amazon.  Console uses '/' as delimiter to organize keys in tree style.  So it doesn't prohibit a key like '/xxxxxx'.  But, AWS::S3::Bucket->file() doesn't handle it properly.

https://github.com/leejo/AWS-S3/blob/master/lib/AWS/S3/Roles/Request.pm#L65
this line will make leading '/' be the delimiter between the host name and  thepath of result URI.
So, it will be removed at S3 server.  For example,
  $bucket->file('/foo/bar')
A key llike '/foo/bar' would be recoganized as 'foo/bar' at servers.

**Comment by leejo** [comment]
Thanks! I'll try to look into this as soon as possible.

**Comment by leejo** [comment]
@ThinkerYzu - v0.17 on its way to CPAN. Could you let me know if this fixes the issue for you?

**Comment by leejo** [comment]
@ThinkerYzu - I realised this needs to be backwards compatible, so I've added another change. The `AWS::S3` constructor can now take an argument, `honor_leading_slashes`, to make sure the requests do not lose those leading slashes. This argument defaults to false. v0.18 on its way to CPAN.
