### ISSUE TITLE
AWS::S3::File->signed_url() sometimes returns invalid URL

### ISSUE THREAD

**Issue by soulchild** [leejo/AWS-S3#3]
The signed URLs returned by signed_url() are quite often invalid, leading to a `SignatureDoesNotMatch` error on AWS. Does this always work on your end and maybe I'm just doing something stupid or is it quite possible that the signing process is somehow flawed?
#### Code

```
my $s3 = AWS::S3->new({
  access_key_id       => $access_key,
  secret_access_key   => $secret_key,
  secure              => 0,
});

my $bucket = $s3->add_bucket(
  name      => $bucket_name,
  location  => '',
);

my $file = $bucket->add_file(
  key       => $filename,
  contents  => \$data,
);

my $expiration_date = time() + 7 * 24 * 60 * 60;
my $url = $ipa_file->signed_url( $expiration_date );
```
#### Check

```
$ curl -I <$url>
HTTP/1.1 403 Forbidden
```

Running the same code again the URL will be correct in some cases.

**Comment by leejo** [comment]
Hmmm, "correct in some cases" sounds like a hash ordering key bug. I thought i got all of these in d9f13a367be1f9382077094e3b82476fceef21d8. Will investigate as soon as i get some time...

**Comment by leejo** [comment]
Oh, do you have the most recent version of the module?

**Comment by soulchild** [comment]
I think so:

```
# perl -MAWS::S3  -e'print $AWS::S3::VERSION'
0.10
```

My perl version is indeed recent enough, so the hash-ordering stuff could be a problem:

```
# perl -V
Summary of my perl5 (revision 5 version 18 subversion 2) configuration:
```

**Comment by leejo** [comment]
OK, i've replicated this - using the test in the dist:

```
AWS_ACCESS_KEY_ID=$key AWS_SECRET_ACCESS_KEY=$secret prove -Ilib -v t/010_basic.t
```

I get URLs that work (they return a HTTP/1.1 307 Temporary Redirect with `curl -I`) in most cases but sometimes they do return a `403` status code. Will investigate a bit more.

**Comment by leejo** [comment]
Looks like this is down to reserved chars being part of the Signature param value.

**Comment by soulchild** [comment]
Do you mean reserved chars in the parameters used in signature() and/or string_to_sign() or in the resulting hashed/encoded signature?

**Comment by leejo** [comment]
`...&Signature=lLnXaOkp6IgDBaFkM+EHW0v3ye0=` doesn't have the `+` percent encoded. I'm just about to push a fix for this and will have it on CPAN within the hour. Thanks!

**Comment by soulchild** [comment]
Nice! Looks like you're right: All URLs with plus signs (and probably other reserved chars) are failing. When manually encoding the chars the URLs become correct. Thanks for the quick fix!

**Comment by dsadinoff** [comment]
I'm seeing the key part of the URL get URL-encoded ,i.e. 
 path/to/file  => path%2Fto%2Ffile

...which is breaking the url.

Is it possible you're URL-encoding too much?

**Comment by leejo** [comment]
> Is it possible you're URL-encoding too much?

Yes, looks like it: https://github.com/leejo/AWS-S3/blob/ea3c1189981cc4a54bfcfd21ebcb916841a96c39/lib/AWS/S3/Roles/Request.pm#L63

Could you open another issue for this one?

**Comment by dsadinoff** [comment]
here you go
https://github.com/leejo/AWS-S3/issues/6
