### ISSUE TITLE
AWS::S3->add_bucket location param is undocumented and buggy

### ISSUE THREAD

**Issue by autarch** [leejo/AWS-S3#9]
This parameter is not documented. While it _shouldn't_ be required, it's passed to the request whether it was specified or not. So if I don't specify it then it ends up being passed as an `undef` and failing the TC for the `AWS::S3::Request::CreateBucket` `location` attribute.

**Comment by leejo** [comment]
Version 0.14 on its way to CPAN shortly. Thanks!

**Comment by autarch** [comment]
Actually, I don't think this fixed it. You can't pass "us-east-1" as a location constraint to S3. It responds with "The specified location-constraint is not valid". I think you can pass any _other_ location though. This is dumb, but that's how S3 defines it.

**Comment by leejo** [comment]
Gah! Thanks for the report, will fix.

**Comment by autarch** [comment]
Actually, that may not be right. I'll explore further.

**Comment by leejo** [comment]
Let me know, I've got a version here ready to upload that passes an empty string as the default rather than `us-east-1`

**Comment by autarch** [comment]
I did some live testing. My PR fixes the issue.

**Comment by leejo** [comment]
Closing - as per #10
